version: '3.8'

services:
  heart-rate-api:
    build: .
    container_name: facial-heart-rate-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=info
    volumes:
      # Data persistence for logs and session data
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Define named volumes for data persistence
volumes:
  app_data:
    driver: local
